# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value
#
services:

    app.form.registration:
        class: AppBundle\Form\RegistrationType
        tags:
            - { name: form.type, alias: app_user_registration }

    app.user.registration.listener:
        class: AppBundle\EventListener\RegistrationListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.custom_auth_failure_handler:
        class: AppBundle\Handler\AuthenticationFailureHandler
        arguments:
            - "@http_kernel"
            - "@security.http_utils"




#    authentication_failure_handler:
#        class: AppBundle\Handler\AuthenticationFailureHandler
#        arguments: ['@router', '@doctrine.orm.entity_manager'], ['@doctrine']

#    app.security.authentication_event_listener:
#        class: AppBundle\EventListener\LoginErrorListener
#        tags:
#            - { name: kernel.event_subscriber }

#    app.user.register.mail:
#        class: AppBundle\EventListener\MailRegistrationListener
#        arguments:
#            - '@router'
#            - '@templating'
#            - '@mailer'
#        tags:
#            - { name: kernel.event_subscriber }

    app.user.photo.upload:
        class: AppBundle\EventListener\PhotoListener
        tags:
            - { name: doctrine.event_listener, event: postPersist }


